# /home/dez/.config/starship.toml
# Starship Prompt using hellwal with safe contrast
format = """
[░▒▓](fg:#%%color7.hex%%)\
[   ](bg:#%%color7.hex%% fg:#%%color0.hex%%)\
[](bg:#%%color4.hex%% fg:#%%color7.hex%%)\
$directory\
[](fg:#%%color4.hex%% bg:#%%color2.hex%%)\
$git_branch\
$git_status\
[](fg:#%%color2.hex%% bg:#%%color1.hex%%)\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#%%color1.hex%% bg:#%%color8.hex%%)\
$time\
[ ](fg:#%%color8.hex%%)\
\n$character
"""
[directory]
style = "fg:#%%color15.hex%% bg:#%%color4.hex%%"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Games" = "󱎓 "
"TV_Shows" = " "
"Movies" = "󰿏 "
"Media" = " "
[git_branch]
symbol = ""
style = "bg:#%%color2.hex%%"
format = '[[ $symbol $branch ](fg:#%%color15.hex%% bg:#%%color2.hex%%)]($style)'
[git_status]
style = "bg:#%%color2.hex%%"
format = '[[($all_status$ahead_behind )](fg:#%%color15.hex%% bg:#%%color2.hex%%)]($style)'
[time]
disabled = false
time_format = "%R"
style = "bg:#%%color8.hex%%"
format = '[[  $time ](fg:#%%color7.hex%% bg:#%%color8.hex%%)]($style)'
[python]
symbol = ""
style = "bg:#%%color1.hex%%"
format = '[[ [$symbol](fg:#FFD43B bg:#%%color1.hex%%)(${{ virtualenv }}) ($version)](fg:#%%color15.hex%% bg:#%%color1.hex%%)]($style)'
python_binary = ["python3", "python"]
[nodejs]
symbol = ""
style = "bg:#%%color1.hex%%"
format = '[[ $symbol ($version) ](fg:#%%color15.hex%% bg:#%%color1.hex%%)]($style)'
[rust]
symbol = ""
style = "bg:#%%color1.hex%%"
format = '[[ $symbol ($version) ](fg:#%%color15.hex%% bg:#%%color1.hex%%)]($style)'
[golang]
symbol = ""
style = "bg:#%%color1.hex%%"
format = '[[ $symbol ($version) ](fg:#%%color15.hex%% bg:#%%color1.hex%%)]($style)'
[php]
symbol = ""
style = "bg:#%%color1.hex%%"
format = '[[ $symbol ($version) ](fg:#%%color15.hex%% bg:#%%color1.hex%%)]($style)'
